### ISSUE TITLE
ThingsML does not compile

### ISSUE THREAD

**Issue by hjnijlunsing** [kpn-iot/thingsml-c-library#11]
Hi I am trying out the Marvin example from thingsML:

Steps:
- Install Arduino IDE (tried both the Windows Store as well as the Website version)
- Install ThingsML library from the Librabry manager (Tester lastest version as well as the previous version)
- Open up ThingsML Marvin example
- Set the board to Arduino Leonardo with appropriate comport
- Compile

Output:
C:\Users\user\Documents\Arduino\libraries\ThingsML\src\senml\actuator\senml_binary_actuator.cpp:17:10: fatal error: cstring: No such file or directory
 #include <cstring>
          ^~~~~~~~~

**Comment by PaulKoning** [comment]
Having similar problems with my ESP32 board using the arduinoesp32 framework in platformio. Many broken includes, inconsistent use of upper and lowercase (which linux really doesn't seem to like). conflicts between base64.h and the base64 implementation of the library.

**Comment by josephverburg** [comment]
The incorrect includes have been fixed in v1.2.1. Thanks for reporting the issue.

@PaulKoning can you colaborate on what is wrong outside from this issue? (preferably in a new issue)

**Comment by hjnijlunsing** [comment]
Thanks! I can confirm that the original issue is solved, for which I will create a separate issue.
