### ISSUE TITLE
ESP8266 - unexpected behaviour when parsing to JSON.

### ISSUE THREAD

**Issue by FlorSanders** [kpn-iot/thingsml-c-library#6]
Compiling the sketch below for the ESP8266-based NodeMCU 1.0, the output on the serial output looks as follows:

`[{"i_":-24, "v":24.0}]`

I'm guessing something goes wrong when parsing the name, because what I'd expect to see was:

`[{"n":"temperature", "v":24.0}]`

Or some output more along those lines.

```cpp
#include <thingsml.h>

SenMLPack device;

SenMLDoubleRecord temperature(THINGSML_TEMPERATURE);

void setup() {
    Serial.begin(9600);
    device.add(temperature);
}

void loop(){
  delay(1000);
    int val = 24;  
    temperature.set(val);
    device.toJson(Serial);        //print to screen
    Serial.println();
}

```

**Comment by josephverburg** [comment]
You are using the THINGSML value, this uses the more space efficient "i_" notation. Also see here: https://docs.kpnthings.com/dm/processing/thingsml

To use a name you can use SENML_NAME_TEMPERATURE instead, see all options here: https://github.com/kpn-iot/thingsml-c-library/blob/master/src/senml/senml_enums.h#L156

**Comment by FlorSanders** [comment]
Oh okay, my bad.
Maybe this could be mentioned a bit more clearly in the documentation.
Anyways, thanks for the reply!
