### ISSUE TITLE
printText stringlength value is wrong. 

### ISSUE THREAD

**Issue by oedze** [kpn-iot/thingsml-c-library#8]
in src/senml/record/senml_record.cpp line 107 should be:
res += printText(F(",\"ut\":"), 6);
instead of 
res += printText(F(",\"ut\":"), 5); Otherwise it will generate invalid json with "ut"1553999 instead of "ut":1553999

**Comment by josephverburg** [comment]
Fixed in v1.1.0, thanks for reporting! 👍
